client.on('message', message => {
	if (message.content === '!ping') {
		message.channel.send('Pong.');}});

- const config = require('./config.json');
+ const { prefix, token } = require('./config.json');

- const config = require('./config.json');
+ const { prefix, token } = require('./config.json');

if (message.content === `${prefix}ping`) 
{	message.channel.send('Pong.');} else if (message.content === `${prefix}beep`) {
	message.channel.send('Boop.');}
  
  else if (message.content === `${prefix}server`) {
	message.channel.send(`This server's kewl name is: ${message.guild.name}`);
}
